# Generated by Django 2.2.5 on 2019-09-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carrea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mat1', models.CharField(max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno')),
            ],
        ),
    ]
