# Generated by Django 2.2.5 on 2019-09-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='Mat1',
        ),
        migrations.AddField(
            model_name='nota',
            name='Fisica',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='POO',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='programación',
            field=models.CharField(default=2, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='sistemas_Operativos',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
